version: "3"

services:
  nuxt:
    build: ./
    container_name: nuxt-website
    restart: always
    ports:
      - "3000:80"
    command:
      "npm run start"

  nginx:
    image: nginx:1.13
    container_name: nuxt-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
